/obj/secure_closet/kitchen/New()
	..()
	sleep(2)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/under/chef(src)
	new /obj/item/clothing/under/chef(src)
	new /obj/item/weapon/kitchen/utensil/fork(src)
	new /obj/item/weapon/kitchen/utensil/knife(src)
	new /obj/item/weapon/kitchen/utensil/spoon(src)
	new /obj/item/weapon/kitchen/rollingpin(src)

/obj/secure_closet/meat/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/faggot(src)
	new /obj/item/weapon/reagent_containers/food/snacks/faggot(src)
	new /obj/item/weapon/reagent_containers/food/snacks/faggot(src)
	new /obj/item/weapon/reagent_containers/food/snacks/faggot(src)

/obj/secure_closet/fridge/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/liq/milk(src)
	new /obj/item/kitchen/egg_box(src)
	new /obj/item/kitchen/egg_box(src)
	new /obj/item/kitchen/egg_box(src)
	new /obj/item/kitchen/egg_box(src)